name: Restrict main PR source

on:
  pull_request:

jobs:
  you-shall-not-master:
    name: Protection of main branch
    runs-on: ubuntu-latest
    steps:
      - name: Allow all except non-staging to main
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"

          if [ "$BASE" != "main" ]; then
            echo "Base branch is '$BASE'. Rule only applies to main. Skipping check."
            exit 0
          fi

          if [ "$BASE" = "main" ] && [ "$HEAD" != "staging" ]; then
            echo "Only PRs from staging to main are allowed."
            exit 1
          fi

          echo "PR from staging to main is allowed."